before_commands:
  - "composer install --prefer-source"

tools: 
  php_code_sniffer:
    enabled: true
    config:
      standard: PSR2
    filter:
      paths: ["module/*/src", "module/*/test"]
  php_cpd:
    enabled: true
    excluded_dirs: ["build", "docs", "module/*/test", "vendor"]
  php_cs_fixer:
    enabled: true
    config:
      level: all
    filter:
      paths: ["module/*/src", "module/*/test"]
  php_loc:
    enabled: true
    excluded_dirs: ["build", "docs", "module/*/test", "vendor"]
  php_mess_detector:
    enabled: true
    filter:
      paths: ["module/*/src"]
  php_pdepend: 
    enabled: true
    excluded_dirs: ["build", "docs", "module/*/test", "vendor"]
  php_analyzer: true
  php_analyzer:
    filter:
      paths: ["module/*/src", "module/*/test"]    
  sensiolabs_security_checker: true  
  
