sudo: false
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

install:
  - composer self-update
  - composer install --dev --prefer-source --no-scripts

before_script:
  - mkdir -p build/coverage
  - mkdir build/logs

script:
  - for d in module/*/test; do echo "Running $d tests"; vendor/bin/phpunit -c "$d/phpunit.xml" --coverage-php "build/coverage/coverage-${d//\//-}.cov" "$d" || exit 1; done

after_script:
  - ./phpcov.phar merge --clover build/logs/clover.xml build/coverage
  - php vendor/bin/coveralls -v

notifications:
  slack: jh:AqFUa4OFXzh9pmAOjYVoOAaV

