<?php if ($this->pageCount): ?>
    <div class="text-center">
        <ul class="pagination pagination-sm">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, ['action' => $this->action, 'id' => $this->id] , ['query' => ['page' => $this->previous]], true); ?>">&laquo;</a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <span>&laquo;</span>
                </li>
            <?php endif; ?>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route, ['action' => $this->action, 'id' => $this->id] , ['query' => ['page' => $page]], true); ?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <span><?php echo $page; ?></span>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, ['action' => $this->action, 'id' => $this->id] , ['query' => ['page' => $this->next]], true); ?>">&raquo;</a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <span>&raquo;</span>
                </li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>