<?php if ($this->pageCount): ?>
    <div class="centre">
        <ul class="pagination">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, array('action' => $this->action, 'id' => $this->id) , array('query' => array('page' => $this->previous))); ?>">&laquo;</a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <span>&laquo;</span>
                </li>
            <?php endif; ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $this->url($this->route, array('action' => $this->action, 'id' => $this->id) , array('query' => array('page' => $page))); ?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <span><?php echo $page; ?></span>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url($this->route, array('action' => $this->action, 'id' => $this->id) , array('query' => array('page' => $this->next))); ?>">&raquo;</a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <span>&raquo;</span>
                </li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>