

<div id="login" class="well center-block">
    <h1 class="text-center"><b>The Hub</b></h1>
    <a href="<?php echo $this->url('scn-social-auth-user/login/provider', array('provider' => 'google')); ?>">
        <img class="center-block" src="/img/google-signin.png" >
    </a>
    <?php foreach ($this->flashMessenger()->setNamespace('zfcuser-login-form') as $message): ?>
        <div class="alert alert-danger text-center login-fail"><?= $message; ?></div>
    <?php endforeach ?>
</div>